export const referenceCompetencies = [
  "Risk Management",
  "Stock Exchange Business and Operation",
  "GCG Principles and Management",
  "Budgeting",
  "Performance Management",
  "Internal Control & Compliance",
  "Akuntansi Perusahaan Efek",
  "Alternative Market Provider Business & Operation",
  "Applied Statistics",
  "Bankruptcy Law",
  "Brokerage Operation",
  "Business Analysis",
  "Business Application System (Core Business Related)",
  "Business Application System (Office Related)",
  "Business Continuity Plan (BCP)",
  "Business Continuity Management",
  "Business Development",
  "Business Performance Management",
  "Business Process Design",
  "Capital Market Instrument",
  "Capital Market Law",
  "Career and Talent Management",
  "Civil Works",
  "Compensation and Benefit Management",
  "Compliance Audit",
  "Contractual Drafting",
  "Corporate Communication and Public Relations",
  "Corporate Finance",
  "Corporate Law",
  "Corporate Legal Document",
  "Corporate Social Responsibility",
  "Corporate Strategic Planning",
  "Culture and Change Management",
  "Database Management System",
  "Datacenter Management",
  "Data Visualization",
  "Data Science",
  "Desktop Management",
  "Digital Media Planning (Social Media & Website)",
  "Econometrics",
  "Economics",
  "Event Management",
  "Exchange Member Report Analisys",
  "Filing System and Administration",
  "Financial Accounting",
  "Financial Analysis",
  "Financial Operation",
  "Financial Planning & Control",
  "Fixed Asset Management",
  "Penanganan Kasus",
  "Industrial Knowledge",
  "Information Security Management",
  "Information System (IS) Application Programming",
  "Information System (IS) Audit",
  "Internal Audit",
  "Inventory Management (Office Supply)",
  "Investigative Audit",
  "Investor and Issuer Candidate Development",
  "Islamic Capital Market",
  "IT Fundamentals",
  "IT Governance and Regulations",
  "IT Infrastructure",
  "IT Quality Assurance",
  "IT Security",
  "IT Service Management",
  "IT System Architecture",
  "Keamanan dan Keselamatan Kerja (K3)",
  "Labour Law and Industrial Relations Regulations",
  "Learning and Development Management",
  "Man Power Planning",
  "Marketing Communication",
  "Protokoler",
  "Mechanical Electrical",
  "Media Placement & Advertising Management",
  "MKBD Evaluation",
  "Money & Foreign Exchange Market Instrument",
  "Money & Foreign Exchange Market Law",
  "Multimedia Communication",
  "Security Office",
  "Office Management",
  "Operating System Management",
  "Organizational Design",
  "Photography",
  "Procurement Management",
  "Project Management",
  "Project Portfolio Management",
  "Public Relation Litigation & Crisis Communication",
  "Quality Management",
  "Recruitment and Selection",
  "Regulation Drafting",
  "Database Management System",
  "Research and Methodology",
  "Security Office",
  "SRO Business and Operation",
  "SRO Regulations",
  "Stock Exchange Regulations",
  "Strategic Marketing",
  "System Modeling",
  "Tax",
  "Teknologi Blockchain",
  "Transformasi Digital",
  "Travel Management",
  "Treasury Management",
  "Vendor Management",
  "Visual Graphic Design",
  "Writing and Reporting Skills",
  "Carbon Exchange Business & Operations",
  "ESG Investing",
  "Building Trust",
  "Integrity",
  "Customer Focus",
  "Strive for Excellence",
  "Facilitating Change",
  "Aligning Performance for Success",
  "Building Partnership",
  "Decision Making",
  "Planning & Organizing",
  "Initiating Action",
  "Gaining Commitment",
  "Negotiation",
  "Continuous Improvement",
  "Executive Disposition",
  "Communicating With Impact",
  "Managing Conflict",
  "Business Orientation",
  "Analytical Thinking",
  "Information Monitoring"
]

